// <auto-generated />
using System;
using ApiAzure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiAzure.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20220413123840_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiAzure.Models.Avion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numAvion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Avions");
                });

            modelBuilder.Entity("ApiAzure.Models.History", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateHist")
                        .HasColumnType("datetime2");

                    b.Property<float>("lat")
                        .HasColumnType("real");

                    b.Property<float>("longe")
                        .HasColumnType("real");

                    b.Property<string>("numVol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("speed")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("ApiAzure.Models.Vol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("arr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_comp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numAvion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numVol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vols");
                });
#pragma warning restore 612, 618
        }
    }
}
